ls:
  .cpp: snake_case
  .c: snake_case
  .hpp: snake_case
  .h: snake_case
  .sh: kebab-case | snake_case
  .py: kebab-case | snake_case
  .cmake: kebab-case | PascalCase
  .mk: lowercase
  ./*/Include:
    .h: regex:^.*$

ignore:
  - build
  - libraries
  - projects/.cmake-format.py
  - projects/UnitTests/Build
  - projects/StaticCodeAnalysis/Build
