minimum_pre_commit_version: '3.2.0'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i, "--style=file"]
        exclude: ^libraries/
      - id: cppcheck
        exclude: ^(libraries)
        args: [--inline-suppr, --suppressions-list=suppressions.txt]
  - repo: https://github.com/cpplint/cpplint/
    rev: 1.6.1  # this is the rev Gen3-Panel uses
    hooks:
      - id: cpplint
        args: ["--verbose=0", --filter=-readability/fn_size]
        exclude: ^libraries/
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    # We use v0.6.11 instead of the latest v0.6.13 because of the following issue:
    # https://github.com/cheshirekow/cmake_format/issues/240
    rev: v0.6.11
    hooks:
      - id: cmake-format
        args: [--in-place, --config-file=projects/.cmake-format.py]
        exclude: ^libraries/
      - id: cmake-lint
        args: [--config-file=projects/.cmake-format.py]
        exclude: ^libraries/
